version: "3.2"
services:
    base:
        build: 
            context: .
            dockerfile: dockerfile/Dockerfile.draco.base
        container_name: scam2020_draco_mono_lns

    experiment:
        build: 
            context: .
            dockerfile: dockerfile/Dockerfile.draco
            args:
                EXPERIMENT_NAME: $EXPERIMENT_NAME
        volumes:
            - ../graphs:/go/src/data/graphs
            - ../experiments/draco_mono_lns/report:/go/src/exp
            - ../experiments/draco_mono_lns/log:/go/src/log
        container_name: scam2020_draco_mono_lns_experiment
        depends_on:
            - base
        deploy:
            resources:
                limits:
                    cpus: '3'
                    memory: 3gb
