version: "3.2"
services:
    base:
        build: 
            context: .
            dockerfile: dockerfile/Dockerfile.draco.base
        container_name: scam2020_draco_multi

    experiment:
        build: 
            context: .
            dockerfile: dockerfile/Dockerfile.draco
            args:
                EXPERIMENT_NAME: $EXPERIMENT_NAME
        volumes:
            - ../graphs:/go/src/data/graphs
            - ../experiments/draco_multi/report:/go/src/exp
            - ../experiments/draco_multi/log:/go/src/log
        container_name: scam2020_draco_multi_experiment
        depends_on:
            - base
